### ISSUE TITLE
Tiny typo: "use" -> "used"

### ISSUE THREAD

**Issue by ghost** [john-b-schneider/uFDTD#12]
On p. 40 of the book, under _Computer Implementation of a One-Dimensional FDTD Simulation_:

![image](https://user-images.githubusercontent.com/4730591/119721262-cf881e00-be1f-11eb-9e79-2895df1c47d8.png)

"use" -> "used"

**Comment by john-b-schneider** [comment]
Indeed!  Thanks for catching that!  (I've fixed that at my own website.  Now to see if I can figure out how to fix that at GitHub.  I'm worse than a newbie when it comes to GitHub, it seems.)
